// Types shared between the server and the browser client.
// Nothing in this file may contain original (unredacted) values.

export type HmacAlgorithm = 'sha256' | 'sha1' | 'sha512';
export type SignatureEncoding = 'hex' | 'base64';

export interface SignatureKey {
  /** Stable identity across edits; generated by the client. */
  id: string;
  /** Non-empty secret. Only ever present in write requests; never returned. */
  secret: string;
  /** Optional label shown in verification details ("new" / "old" / ...). */
  label?: string;
}

export interface SignatureConfig {
  /** Header carrying the signature, e.g. "X-Signature". */
  header: string;
  /** Header carrying the timestamp. Absent => no timestamp window check. */
  timestampHeader?: string;
  /** Allowed clock skew in seconds (absolute). */
  toleranceSeconds: number;
  algorithm: HmacAlgorithm;
  encoding: SignatureEncoding;
  /** Both keys are accepted; first match wins. Useful during key rotation. */
  keys: SignatureKey[];
  /** What the remote side signs. */
  signedContent: 'rawBody' | 'timestampDotRawBody';
}

export type RuleAction = 'drop' | 'replace' | 'tail';

export interface RedactionRule {
  id: string;
  /** Where the rule finds its target. */
  scope: 'header' | 'body';
  /** Header name (scope=header, case-insensitive) or JSON path (scope=body). */
  target: string;
  action: RuleAction;
  /** action=replace: fixed replacement text. */
  replacement?: string;
  /** action=tail: number of trailing characters to keep. */
  keepLast?: number;
}

export interface Source {
  name: string;
  /** Base URL replayed requests are sent to. Empty => replay disabled. */
  targetUrl: string;
  signature: SignatureConfig | null;
  rules: RedactionRule[];
  createdAt: number;
}

export type VerifyStatus =
  | 'not_configured'
  | 'missing_signature'
  | 'timestamp_invalid'
  | 'timestamp_skew'
  | 'malformed_signature'
  | 'mismatch'
  | 'valid';

export interface VerificationResult {
  status: VerifyStatus;
  /** Human-readable detail. Never includes the received signature or body. */
  detail: string;
  /** Key label that matched, when status=valid. */
  matchedKeyLabel?: string;
}

export type BodyKind = 'json' | 'form' | 'text' | 'empty';

export interface ReplayRecord {
  id: number;
  at: number;
  statusCode: number | null;
  /** Round-trip time in milliseconds. */
  durationMs: number;
  ok: boolean;
  /** Failure reason; never includes request content. */
  error?: string;
}

export interface EventRecord {
  id: number;
  source: string;
  method: string;
  /** Full path including query string, relative to /hook/:source. */
  path: string;
  /** Query string without the leading "?", or "". */
  query: string;
  headers: Record<string, string>;
  bodyKind: BodyKind;
  /** Redacted parsed body for json/form (null for text/empty). */
  bodyTree: unknown;
  /** Redacted bytes as text (json re-serialised, form re-encoded, text masked). */
  bodyText: string;
  bodyBytes: number;
  receivedAt: number;
  verification: VerificationResult;
  replays: ReplayRecord[];
}

export interface SourcesPayload {
  sources: Source[];
}

/** A source as returned by the API: secrets are never echoed back. */
export interface SourceView extends Omit<Source, 'signature'> {
  signature: (Omit<NonNullable<Source['signature']>, 'keys'> & {
    keys: Array<{id: string; label?: string}>;
  }) | null;
}

export interface PreviewRequest {
  headers: Record<string, string>;
  /** Content-Type hint; when absent the body is treated as text. */
  contentType?: string;
  /** Raw sample body text. */
  body: string;
  rules: RedactionRule[];
}

export interface PreviewResponse {
  headers: Record<string, string>;
  bodyKind: BodyKind;
  /** Before/after parsed tree for json/form, else null. */
  beforeTree: unknown;
  afterTree: unknown;
  beforeText: string;
  afterText: string;
}

export interface PathCheckResponse {
  valid: boolean;
  errorAt?: number;
  message?: string;
}

export interface ReplayResponseItem {
  eventId: number;
  replay: ReplayRecord;
}
